apiVersion: v1
kind: ServiceAccount
metadata:
  name:  resource-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  resource-manager
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create","delete"]


---